name: Build and Deploy

on:
  schedule:
  - cron: '0 0 * * *'

jobs:
  buildWebsite:
    
    env:
      GITLAB_PRIVATE_TOKEN: ${{ secrets.GITLAB_PRIVATE_TOKEN }}   
    
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Use actions/checkout@v1
      uses: actions/checkout@v1
    
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7.x'
    
    - name: Install PIP packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Install Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
        registry-url: 'https://registry.npmjs.org'
      
    - name: Install NPM packages
      run: |
        npm install
        dependencies=('bootstrap' 'jquery' 'popper.js' '@fortawesome')
        for dependency in "${dependencies[@]}"
        do
          mv node_modules/${dependency} src/static -f
          echo "Moved ${dependency} to /src/static folder"
        done

    - name: Compile SASS
      run: |
        npm run compile-sass
        
    - name: Build website and artifacts
      run: |
        cd src
        python fetch.py
        python process.py
        python freeze.py
        mkdir -p artifacts
        mv build artifacts -f
        mv data artifacts -f
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: artifacts
        path: src/artifacts
        
  commitAndPushWebsite:
    
    needs: buildWebsite
    
    env:
      REMOTE_BRANCH: website
      
    runs-on: ubuntu-latest
    
    steps:
    - name: Clone the repoitory
      uses: actions/checkout@v1
    
    - name: Configure Git
      run: |
        git checkout -f ${REMOTE_BRANCH}
        git config --global user.email ${GITHUB_ACTOR}@gmail.com
        git config --global user.name ${GITHUB_ACTOR}
    
    - name: Download artifacts
      uses: actions/download-artifact@v1
      with:
        name: artifacts
        path: artifacts
    
    - name: Commit and Push
      run: |
        git add -f artifacts/data
        git commit -m "gh-actions updated website data"
        git add -f artifacts/build
        git commit -m "gh-actions updated website build"
        git push --force https://${GITHUB_ACTOR}:${{secrets.GITHUB_TOKEN}}@github.com/${GITHUB_REPOSITORY}.git HEAD:${REMOTE_BRANCH}
